### ISSUE TITLE
Math behind geometry

### ISSUE THREAD

**Issue by JL978** [kevin-shannon/3D-FlowerBox#1]
Hello, I'm just trying to understand the math behind how the geometry is created/updated and I can't quite understand the code. Would you mind giving an explanation or pointing to a resource with an explanation? Thanks!

**Comment by kevin-shannon** [comment]
At morph=0 it's a box, at morph=1 it's a sphere. The rest is linear interpolation from overshoot.

https://github.com/kevin-shannon/3D-FlowerBox/blob/ff02e8496f05a8574383fb6e1e4c5b18db4ba1e4/geometry.js#L45

This is the magic line.
